version: "3"

services:
  redis:
    container_name: wikat_redis
    restart: always
    image: redis/redis-stack:latest
    ports:
      - ${REDIS_PORT}:6379
    volumes: 
      - ./redis:/data
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    ports:
    - "8081:8081"
